### ISSUE TITLE
stable and full feature?

### ISSUE THREAD

**Issue by fognome** [arangodb/go-driver#100]
Is this driver stable enough for production? And does it support full feature of the latest version of ArangoDB?

**Comment by ewoutp** [comment]
@fognome The go driver is being used in many places already.
We're aware of some issues with the VST connection under heavy load, but the HTTP connection (which is recommend is most cases) is fully stable.

Feature wise you can do everything you typically want for a database application. Very specific API (e.g. related to replication config) are not all supported yet.
If you see a missing feature that you have a usecase for, please let us know.
