### ISSUE TITLE
driver does not seem to decode numeric timestamps to time.Time

### ISSUE THREAD

**Issue by kmanley** [arangodb/go-driver#102]
I have json data in arango with times stored as numeric time (milliseconds elapsed since Unix epoch)
When I use the driver to try to read data into a struct with field time.Time, I get error

```2018/03/16 23:32:17 parsing time "1507900413446" as ""2006-01-02T15:04:05Z07:00"": cannot parse "1507900413446" as """```

**Comment by kmanley** [comment]
I guess this is just delegating to the default json unmarshaler in the go stdlib. So to fix this I would need to change the type in my structs from time.Time to some custom type and implement UnmarshalJSON on it.

**Comment by ewoutp** [comment]
The default parser for `time.Time` uses RFC3339 format (like javascript does).
If your data comes out of the database in a different format, you should indeed use a another type or derive from `time.Time` and add a custom (un)marshaller.
