### ISSUE TITLE
Query "return null" make the panic: runtime error

### ISSUE THREAD

**Issue by mhseptiadi** [arangodb/go-driver#117]
Please help:

I try to run this
```
	var result interface{}
	query = "return null"

	ctx := context.Background()
	cursor, err := connector.ArangoDB.Query(ctx, query, nil)
	if err != nil {
		log.Println("err1",err) //no error print here
	}
	defer cursor.Close()
	meta, err := cursor.ReadDocument(ctx, &result)
        //panic: runtime error: invalid memory address or nil pointer dereference

	if(err != nil){
		log.Println("err2",err) //no error print here either
	}
	log.Println("meta",meta)
```
then got error `panic: runtime error: invalid memory address or nil pointer dereference`.

Just for testing purpose, the query i change it into `return null`. The real query that return null is longer, and im sure the query run well on arangodb.

**Comment by Mitranim** [comment]
Having the same issue. For me, it happens when requesting a non-existing document. Traced the problem to `cursor.ReadDocument`: it tries to unmarshal `c.Results[index]` which contains a nil pointer. Source line: [[1]](https://github.com/arangodb/go-driver/blob/52a597d923de0f37450b06984ac945cab6707c8e/cursor_impl.go#L168). The issue is probably due to this nil pointer.

**Comment by Mitranim** [comment]
Any good workarounds?

**Comment by Mitranim** [comment]
Hmm apparently the workaround above doesn't quite work, because `cursor.Count()` can somehow be `0` for an _existing_ document. Running the exact same query from `arangosh` produces a cursor with `count: 1`.

Had to resort to `defer / recover` and checking for a nil pointer error.

**Comment by Mitranim** [comment]
Thanks for the fix, but... I don't think it actually works. Now, upon decoding a `[null]` response, the driver returns `DocumentMeta{}, nil`, where the document meta is completely empty. In my opinion, this should never be returned from a query. It should use a `NoMoreDocumentsError`.

**Comment by Mitranim** [comment]
Upon further consideration, that was just my ignorance talking. It seems that queries like `return document(coll, key)` are _supposed_ to return `[null]` if the document is not found. I expected the driver to handle this by returning a `NoMoreDocumentsError`, but this would be incorrect when you have something like `[null, <doc>]`. As a result, `DocumentMeta{}, nil` is a fairly logical solution, but you have to be aware of the possibility of `meta.Key == ""`.
