### ISSUE TITLE
Graph Support

### ISSUE THREAD

**Issue by mvbaffa** [arangodb/go-driver#135]
Hi,

Do you have any examples of graph creation and support. I would like to work with Go but I could not find real examples about graph support

Thanks

**Comment by DavidJohnGee** [comment]
Any examples with graphs would be super useful please!!!!

**Comment by lamai93** [comment]
Now there is `example_graph_test.go` in the repository root. [Click](https://github.com/arangodb/go-driver/blob/master/example_graph_test.go).
