### ISSUE TITLE
Structs with key specified don't read the key

### ISSUE THREAD

**Issue by peterlamar** [arangodb/go-driver#138]
The following creates the book document but does not use the key. Is this intended behavior?

	book := Book{
		_key:    234234343,
		Title:   "ArangoDB Cookbook",
		NoPages: 257,
	}
	
	meta, err := collection.CreateDocument(nil, book)

**Comment by peterlamar** [comment]
Here is the whole example, perhaps I am doing a simple error 

package main

import (
	"fmt"

	driver "github.com/arangodb/go-driver"
	"github.com/arangodb/go-driver/http"
)

type Book struct {
	_key    string
	Title   string
	NoPages int
}

func main() {

	conn, err := http.NewConnection(http.ConnectionConfig{
		Endpoints: []string{"http://localhost:8529"},
	})
	if err != nil {
		// Handle error
	}
	c, err := driver.NewClient(driver.ClientConfig{
		Connection: conn,
	})
	if err != nil {
		// Handle error
	}

	// Open "examples_books" database
	db, err := c.Database(nil, "examples_books")
	if err != nil {
		// Handle error
	}

	// Open "books" collection
	col, err := db.Collection(nil, "books")
	if err != nil {
		// Handle error
	}

	// Create document
	book := Book{
		_key:    "234234343",
		Title:   "ArangoDB Cookbook",
		NoPages: 257,
	}

	col.CreateDocument(nil, book)

	fmt.Printf("Created document in collection '%s' in database '%s'\n", col.Name(), db.Name())
}

**Comment by ewoutp** [comment]
This behavior is caused by the json marshaller in go. Use something like
this:

Key string `json:"_key"`

Ewout

Op vr 13 jul. 2018 18:53 schreef Peter Lamar <notifications@github.com>:

**Comment by peterlamar** [comment]
Thanks and i really appreciate it, that worked! Thats certainly not where I would have started looking for the issue.

Fix : 

type Book struct {
	Key     string `json:"_key"`
	Title   string
	NoPages int
}
