### ISSUE TITLE
cursor.Count malfunction

### ISSUE THREAD

**Issue by romshark** [arangodb/go-driver#141]
## Expected Behavior
I expect the `cursor` returned by `db.Query()` to return the number of results from `cursor.Count()` because the [documentation states that it'll default to true, even if `WithQueryCount` is not set.](https://godoc.org/github.com/arangodb/go-driver#WithQueryCount)

## Actual Behavior
Meanwhile the following code...
```go
var tm TeamMember
_, err := dbTeam.ReadDocument(ctx, "a0000000000000000000000000000002", &tm)
log.Print("READ DOCUMENT: ", err, " | ", tm)

// Query document
cursor, err := db.Query(
    ctx,
    `FOR t IN team
        FILTER t.email == @email
        RETURN t`,
    varMap{
        "email": "test@mail.com",
    },
)
if err != nil {
    return nil, fmt.Errorf("Query failed: %s", err)
}
defer cursor.Close()

// Check whether found or not
cursorCount := cursor.Count()
log.Print("CURSOR COUNT: ", cursorCount)
if cursorCount < 1 {
    return nil, nil
}
```

produces the following logs:
```
READ DOCUMENT: <nil> | {{[160 0 0 0 0 0 0 0 0 0 0 0 0 0 0 2]} {test@mail.com} TestFirstName TestLastName 2018-08-06 02:01:51 +0000 UTC [sampleRole] testpassword}
2018/08/06 04:01:51 CURSOR COUNT: 0
```

It seems that even though `cursor.ReadDocument()` reads the correct document - `cursor.Count()` still returns `0`. It'll only return `1` when a context produced by `WithQueryCount(ctx, true)` is excplicitly passed to the query method. This behavior doesn't match the [documentation](https://godoc.org/github.com/arangodb/go-driver#WithQueryCount) though and looks like a bug.

## Environment
|  |  |
|:-|-|
| ArangoDB version | 3.3.13 |
| arangodb/go-driver | 2b539b8ac3117b3dbc3d258301352007e833f14b |
| Platform | Windows 10 x86_64 (Docker, arangodb:latest) |

**Comment by ewoutp** [comment]
The documentation that you're referring to states that the default value of the argument of `WithQueryCount` defaults to true (if you do not provide this optional second argument).
It is really intended that you need to prepare a context with `WithQueryCount` if you want to get a non-zero return from `Count`.

**Comment by romshark** [comment]
I see, seems like I misinterpreted the documentation there. Though I wonder how sometimes it does return a correct count even though the context wasn't prepared while another time it won't, that's what lead me to the misinterpretation in the end.
