### ISSUE TITLE
Add transaction examples

### ISSUE THREAD

**Issue by romshark** [arangodb/go-driver#143]
The [ExampleRequests](https://github.com/arangodb/go-driver/blob/master/docs/Drivers/GO/ExampleRequests/README.md) page doesn't list any multi-collection transaction examples so far. I think I'd make sense to add a few at least because there are some unclear situtations like this one for example: In the [official ArangoDB documentation](https://docs.arangodb.com/3.3/Manual/Transactions/TransactionInvocation.html) there's only JavaScript examples in which the affected collections are declared right within the JS code:
```js
collections: {
	write: [ "users", "logins" ],
	read: [ "recommendations" ]
}
```
Though in the documentation of arangodb/go-driver the [Database.Transaction](https://godoc.org/github.com/arangodb/go-driver#Database) method takes an optional [TransactionOptions](https://godoc.org/github.com/arangodb/go-driver#TransactionOptions) object, which also provides `ReadCollections` and `WriteCollections` options, which is obviously confusing.
I assume that `Database.Transaction` takes the code block of the `action` functor from the documentation examples and thus the options must not be declared in the JS code, but the library docs don't explain this properly.

To avoid such confusion - additional transactions examples would be very useful!

**Comment by dalu** [comment]
I'd like to extend on that, add proper, working examples
One main type and an associated type e.g. Teacher and Student/s.
From connecting to disconnecting ( and all the CRUD inbetween, and not all in 1 function with context reuse)

**Comment by Thebigwind** [comment]
still no  list any multi-collection transaction examples so far?

**Comment by Sufod** [comment]
I'm also looking for a working example on how tu use transactions to save elements in a list

**Comment by aaqibb13** [comment]
Looks like there are examples for anything other than transactions for the subtlety of those operations.

**Comment by nikita-vanyasin** [comment]
Hello @romshark 

Thanks for you feedback!

Unfortunately, in go-driver v1 there is no direct support for database transactions.

More advanced transaction functions are available in [go-driver/v2](https://github.com/arangodb/go-driver/tree/master/v2), which is still under development. 
You can see transaction usage examples here: https://github.com/arangodb/go-driver/issues/382#issuecomment-1070756082
We will improve our docs for transactions and many other things when v2 will have a stable release.

Best,
Nikita
