### ISSUE TITLE
WithReturnNew does not return _to & _from in edge collections

### ISSUE THREAD

**Issue by MrDHat** [arangodb/go-driver#152]
When using `WithReturnNew` in the context to `CreateDocuments`, `_to` & `_from` values are not returned. Is this by design or am I doing something wrong?

This is what my code looks like:
```
        savedDocs := make([]models.SomeModel, len(docs))
	ctx := context.Background()
	retCtx := arango.WithReturnNew(ctx, savedDocs)
	_, errs, err := c.CreateDocuments(retCtx, docs)
```

**Comment by lamai93** [comment]
Please make sure, that you use a `EdgeCollection`. Otherwise `_from` and `_to` are ignored.
