### ISSUE TITLE
Add edge index support

### ISSUE THREAD

**Issue by elvuel** [arangodb/go-driver#176]
**ArangoDB:** 3.4.2

the edge collection [_from, _to] index type is 'edge', list all indexes in the collection returns error.

```golang
// indexStringToType converts a string representation of an index to IndexType
func indexStringToType(indexTypeString string) (IndexType, error) {
	switch indexTypeString {
	case string(FullTextIndex):
		return FullTextIndex, nil
	case string(HashIndex):
		return HashIndex, nil
	case string(SkipListIndex):
		return SkipListIndex, nil
	case string(PrimaryIndex):
		return PrimaryIndex, nil
	case string(PersistentIndex):
		return PersistentIndex, nil
	case string(GeoIndex), "geo1", "geo2":
		return GeoIndex, nil

	default:
		return "", WithStack(InvalidArgumentError{Message: "unknown index type"})
	}
}
```

**Comment by Simran-B** [comment]
EdgeIndex is also missing here:
https://github.com/arangodb/go-driver/blob/master/index.go

**Comment by maierlars** [comment]
The Edge Index is a system index and is, like the primary index, not displayed or accessible.

**Comment by elvuel** [comment]
@maierlars  :ok_hand:, but list indexes for collection contains Edge Index should ignore the error.

**Comment by maierlars** [comment]
Ah got it! Asking for indices on a Edge Collection always returns an error because the edge index is not filtered out.

**Comment by maierlars** [comment]
Fixed
