### ISSUE TITLE
cursor.Count() returned the LIMIT value

### ISSUE THREAD

**Issue by Fruchtgummi** [arangodb/go-driver#178]
```go
ctx := driver.WithQueryCount(context.Background())
	query := ` FOR d IN cd_data_subject`

	if table.Search[0] != "" {
		query += ` FILTER (`
		query += ` d.Title.Lang LIKE "` + table.Search[0] + `%"`
		query += `)`
	}
	query += ` LIMIT ` + table.Offset[0] + `, ` + table.Limit[0] + `
				SORT d.` + table.Sort[0] + ` ` + table.Order[0] + `

				RETURN MERGE(d,{
					Title: { 
						Lang: {
							SelectedLang: TRANSLATE(@Lang, d.Title.Lang, "translate not found!")
							}
					}
				})
				
				`
	bindVars := map[string]interface{}{
		"Lang": helper.GetSessionValue(r, "mylang"),
	}

	cursor, err := arangodb.Db.Query(ctx, query, bindVars)
	if err != nil {
		myerrf.Message = err.Error()
		myerrf.Namevalue = ""

		return nil, myerrf
	}

	defer cursor.Close()
	total := cursor.Count()
```

Count have the LIMIT value

**Comment by maierlars** [comment]
Please elaborate. What is the expected behavior and what is the actual behavior?

**Comment by Fruchtgummi** [comment]
In cursor.Count() is not the full count of all datas, but only my own LIMIT value. I need all rows on my request, to realize a pagination.

**Comment by Fruchtgummi** [comment]
if I user `WithQueryFullCount` give me 0 back.

**Comment by maierlars** [comment]
This is not enough information. Which version of arangodb? `WithQueryFullCount` is the right approach. And without further details on how it is used, I can just say: works for me, and I added a test to ensure it does.

However, please note that `LIMIT` _before_ `SORT` is most likely **not** what you want.

**Comment by ecarter202** [comment]
> if I user `WithQueryFullCount` give me 0 back.

were you able to figure this out? thanks.

**Comment by Fruchtgummi** [comment]
yes

if I use `driver.WithQueryFullCount(context.Background())`

then get the right value with `cursor.Statistics().FullCount()`
