### ISSUE TITLE
Missing json attributes on CreateGraphOptions struct

### ISSUE THREAD

**Issue by 345paul** [arangodb/go-driver#180]
The `CreateGraphOptions` struct type in the file https://github.com/arangodb/go-driver/blob/master/database_graphs.go is missing json attributes, which is a bit inconsistent compared to `CreateCollectionOptions`, `CreateDatabaseOptions` and other types.

Is there a reason why this type doesn't have the attributes, or is it just an oversight?

**Comment by maierlars** [comment]
This is because internally the options are rewritten in a different format. On the other hand the other `*Options` are passed directly to the api as serialized json object.

**Comment by 345paul** [comment]
Ok, thanks for the response.
