### ISSUE TITLE
After Querying documents from collection have no Update Count in cursor

### ISSUE THREAD

**Issue by kubitre** [arangodb/go-driver#189]
I have problems with the Count () method. This method returns 0 after I requested several documents from the collection, but in the debugger I have documents

my code sample:
```(go)
query := "FOR d IN users FILTER d.user_name == @name RETURN d"
	bindVars := map[string]interface{}{
		"name": username}

	ctx := context.Background()
	cursor, err2 := (*dao.Database.Database).Query(ctx, query, bindVars)
	if err2 != nil {
		return false, err2
	}
	defer cursor.Close()
	// key := ""
	for {
		var document *models.User
		meta, err3 := cursor.ReadDocument(ctx, &document)
		// key = meta.Key
		if driver.IsNoMoreDocuments(err3) {
			break
		} else if err3 != nil {
			return false, err3
		}
		fmt.Println(nameServer+"Get document: ", document, " key: ", meta.Key)
	}
	if cursor.Count() > 0 {
		return true, nil
	}
```

In debugger i have this:
![image](https://user-images.githubusercontent.com/32496864/58369296-92cc7800-7f22-11e9-9d0b-fd113f0c31be.png)

result array have 1 document, but count field equal 0

**Comment by kubitre** [comment]
@maierlars need help

**Comment by its-smesh** [comment]
Is this issue resolved? I'm facing the same issue. Refer https://stackoverflow.com/questions/59979298/golang-arangodb-driver-querying-documents-with-bind-variables-not-working .

**Comment by kubitre** [comment]
no

**Comment by its-smesh** [comment]
I tried the following

```
        pCtx := context.Background()
        //using WithQueryCount fixes the count for AQL queries. Not sure if the same would work for ReadDocument as well
	ctx := arangodbdriver.WithQueryCount(pCtx)

	// Open database
	db, err := s.dbClient.Database(pCtx, databaseName)
	if err != nil {
		return nil, 0, 0, errors.New(err, fmt.Sprintf("failed to open [%s] database", databaseName))
	}

	var overallCount int64 = 0
        // using nil instead of the bindVar, since the bindVar is not working. Iterating through the cursor works, but bindVars aren't.
	cursor, err := db.Query(ctx, qs, nil)
```

**Comment by kubitre** [comment]
ok, i try this and answer

**Comment by xScorp1oNx** [comment]
> I tried the following
> 
> ```
>         pCtx := context.Background()
>         //using WithQueryCount fixes the count for AQL queries. Not sure if the same would work for ReadDocument as well
> 	ctx := arangodbdriver.WithQueryCount(pCtx)
> 
> 	// Open database
> 	db, err := s.dbClient.Database(pCtx, databaseName)
> 	if err != nil {
> 		return nil, 0, 0, errors.New(err, fmt.Sprintf("failed to open [%s] database", databaseName))
> 	}
> 
> 	var overallCount int64 = 0
>         // using nil instead of the bindVar, since the bindVar is not working. Iterating through the cursor works, but bindVars aren't.
> 	cursor, err := db.Query(ctx, qs, nil)
> ```

It's work for me! Thanks

**Comment by nikita-vanyasin** [comment]
Looks like the issue resolved.
Feel free to reopen if you still have questions.

Best,
Nikita
