### ISSUE TITLE
Version tags

### ISSUE THREAD

**Issue by Imprtat** [arangodb/go-driver#192]
Hi guys,

Could you please create version tags as recommended by Go Modules guide https://github.com/golang/go/wiki/Modules#what-happens-if-i-create-a-gomod-but-do-not-apply-semver-tags-to-my-repository :
> In order to provide the best experience for consumers, module authors are encouraged to apply semver VCS tags (e.g., v0.1.0 or v1.2.3-rc.1)

Lack of tags do not allow to index actual versions in gocenter, because of 
https://github.com/jfrog/gocenter/wiki/How-GoCenter-Works#project-inclusion-criteria:
> The GitHub project should have version tags in the v<semver> format, e.g., v1.0.0 as per the Go module standard. There should be new version tags created within the last year to ensure GoCenter doesn't pull in legacy tags. If no matching tags are found, GoCenter will consume the latest commit on the master branch.
> As a general rule, once the master branch has been consumed as a v0.0.0-commit hash version, GoCenter will refuse new version requests. You should gently request the library owner to use version tagging as best practice.

For me it's an issue because company I work for allows to use only those dependencies which are present in the gocenter.io.

Thanks,
Vitalii

**Comment by omenos** [comment]
An aside on this as there are current git tags, the lack of the 'v' prefix means that the module will use the pseudo version rather than the tag name. These pseudo versions are what will be committed in `go.mod` and `go.sum`. Examples:

```bash
$ go get github.com/arangodb/go-driver@v1.1.0
invalid version: unknown revision v1.1.0

$ go get github.com/arangodb/go-driver@1.1.0
go: downloading github.com/arangodb/go-driver v0.0.0-20200811070917-cc2b983cf602
go: github.com/arangodb/go-driver 1.1.0 => v0.0.0-20200811070917-cc2b983cf602
go: downloading github.com/pkg/errors v0.8.1
go: downloading github.com/arangodb/go-velocypack v0.0.0-20200318135517-5af53c29c67e

$ go get github.com/arangodb/go-driver # Equates to default branch latest commit rather than greatest tag
go: github.com/arangodb/go-driver upgrade => v0.0.0-20200831144536-17278d36b7e8
go: downloading github.com/arangodb/go-driver v0.0.0-20200831144536-17278d36b7e8
go: downloading github.com/pkg/errors v0.9.1
```

Counter example with spf13/cobra:
```bash
$ go get github.com/spf13/cobra # Pulls latest tag rather than latest commit
go: downloading github.com/spf13/cobra v1.0.0
go: github.com/spf13/cobra upgrade => v1.0.0
go: downloading github.com/inconshreveable/mousetrap v1.0.0
go: downloading github.com/spf13/pflag v1.0.3
```

Relevant parts of go.mod/sum after the above commands (sum stripped of hashes):
```bash
    github.com/arangodb/go-driver v0.0.0-20200831144536-17278d36b7e8
    github.com/spf13/cobra v1.0.0
```

**Comment by irridia** [comment]
This. I mentioned this in another issue or PR and just saw this. +1.

**Comment by MichaBub** [comment]
Please use correct versioning

**Comment by nikita-vanyasin** [comment]
Closing: the correct version tags applied since `v1.2.1`
