### ISSUE TITLE
Attribute with state false 

### ISSUE THREAD

**Issue by Fruchtgummi** [arangodb/go-driver#195]
Hi 

is maybe a bug! ;)

Driver for GOLANG

I have a struct with a bool value:

![image](https://user-images.githubusercontent.com/2059888/61040155-5d93c080-a3d0-11e9-90f1-296432bd1223.png)

If I set the value on false by the `IsActive bool `json:",omitempty"``, the stat false is not transferred to the database. If remove ``json:",omitempty"`` then set on database. 

The value "false", should always be taken over, especially when I put it explicitly. Then the value is not empty! :D

**Comment by maierlars** [comment]
Are you using HTTP+JSON or VST+VPACK for your connection?

**Comment by maierlars** [comment]
This is intended behavior. A value is empty if its the default value. This is what the Go JSON Marshal does.
See here: https://play.golang.org/p/EvHfH8M1H9q

By the way: when is a bool empty?

**Comment by Fruchtgummi** [comment]
The bool value ist not empty from my site. If i set the value to false, with option `json:",omitempty"`` `, then missing the key and value in to database. 

If I set the value explicit of false, then that should be the same in my database.

**Comment by ajanikow** [comment]
Hello!

It is a problem of file type you choose and GO JSON Marshaller. If we use `bool` false value is omitted by default - and the default value for `bool` is false:

```
type s struct {
    MyFlag bool `json:",omitempty"`
}

json.Marshal(s{}) -> '{}'

json.Marshal(s{false}) -> '{}'

json.Marshal(s{true}) -> '{"MyFlag":true}'
```

If you want to put also false value (if is set) you can use type `*bool` and `omitempty` flag. In this case, only `nil` (defaut) value will be omitted:

```
type s struct {
    MyFlag *bool `json:",omitempty"`
}

trueVar := true
falseVar := false

json.Marshal(s{}) -> '{}'

json.Marshal(s{&falseVar}) -> '{"MyFlag":false}'

json.Marshal(s{&trueVar}) -> '{"MyFlag":true}'
```

Best Regards,
Adam Janikowski.
