### ISSUE TITLE
cursor implementation when running queries with non-Document return values

### ISSUE THREAD

**Issue by cmeon** [arangodb/go-driver#20]
First off thank you for this driver and especially the comprehensive errors returned.
One thing though, when running a query with return value other than the document like:
```go
cursor, err := db.Query(
        ctx,
        "insert @doc in @@col return NEW.field_of_type_string",
        map[string]interface{}{
                "doc": someDoc,
                "@col": collectionName,
       },
)
```
Results in an error:
`json: cannot unmarshal string into Go value of type driver.DocumentMeta`

I was thinking of ignoring the error returned [here](https://github.com/arangodb/go-driver/blob/master/cursor_impl.go#L147). That way in case the user returns a value
with `DocumentMeta` fields, it doesn't fail.

**Comment by ewoutp** [comment]
Thanks for reporting. I have a pretty good idea what is causing this. We'll investigate and fix.

PS. Sorry for the delay.

**Comment by ewoutp** [comment]
Problem reproduced.

**Comment by ewoutp** [comment]
Fixed in master. Please retry.

**Comment by cmeon** [comment]
Cool! Thanks. 😊
