### ISSUE TITLE
Is coll.UpdateDocuments() atomic?

### ISSUE THREAD

**Issue by amarjeetanandsingh** [arangodb/go-driver#211]
If i  use collection.UpdateDocuments(ctx, nil, []doc with _key), does it ensures atomic update?

If there are 2 documents in doc[], and if the update of first document fails, does it guarantees that the update of 2nd document will also fail OR will be reverted back? 

Can't find any info in documentation.

https://github.com/arangodb/go-driver/blob/4407cf842de1caa5ffb8da86d6d46ee1ecc5c8c5/collection_document_impl.go#L289

**Comment by maierlars** [comment]
Single Server yes, Cluster no.

**Comment by amarjeetanandsingh** [comment]
thanks :)

**Comment by amarjeetanandsingh** [comment]
but it would be better if its documented somewhere

**Comment by amarjeetanandsingh** [comment]
@maierlars 
Can i raise a PR with the doc change?

**Comment by maierlars** [comment]
this is unrelated to the go-driver which functions just as an programming interface against the http api.
