### ISSUE TITLE
CreateGraphOptions Missing ReplicationFactor in go driver.

### ISSUE THREAD

**Issue by bandikishores** [arangodb/go-driver#227]
Hi,

I'm trying to connect to an arangodb.cloud instance using go-driver.

When I try to create a Graph using [CreateGraph](https://github.com/arangodb/go-driver/blob/master/database_graphs.go#L41) I end up with the error.

> replicationFactor must not be lower than minimum allowed replicationFactor (3)

I don't see an option to set `replicationFactor` to Graphs in **go-driver**, however I see this option in [Java Driver](https://github.com/arangodb/arangodb-java-driver/blob/master/src/main/java/com/arangodb/model/GraphCreateOptions.java#L110).

This is my Sample Create Graph Call:
```
	var def driver.EdgeDefinition
	def.Collection = c.Config.EdgeCollection
	def.From = []string{"org"}
	def.To = []string{"user"}

	var options driver.CreateGraphOptions
	options.EdgeDefinitions = []driver.EdgeDefinition{def}

	_, err = db.CreateGraph(ctx, c.Config.ResourceGraph, &options)
```

This call works in my local, where I've just one instance. Is there a way to pass replicationFactor to this call?

**Comment by Skarlso** [comment]
@bandikishores Hi. though the related issue appears to be open, it seems this has been fixed:
https://github.com/arangodb/go-driver/pull/230

**Comment by bandikishores** [comment]
Hi @Skarlso , It works now. Thanks 👍

**Comment by Skarlso** [comment]
Thanks!
