### ISSUE TITLE
Error:  database.Query ignores WithMaxQueryRuntime

### ISSUE THREAD

**Issue by noahsilverman** [arangodb/go-driver#248]
I have a long running query, that takes around 30 minutes.  Sending the query using this go-driver always results in a timeout error. "Post http://localhost:8529/_db/mydb/_api/cursor: context deadline exceeded" after exactly 9 minutes.

I read, in the documentation, about using either WithMaxQueryRuntime or WithMaxQueryTTL in the context.  Neither has any effect on the timeout.

	ctx = driver.WithQueryTTL(ctx, time.Duration(120*time.Minute))
	query := "FOR v,e,p in 1..1000 OUTBOUND \"root/start\"  work  FILTER v._id == \"endpoint\" RETURN p.edges"
	cursor, err := db.Query(ctx, query, nil)
	if err != nil {
		log.Error(err)
	}
    ERRO[0540] Post http://localhost:8529/_db/mydb/_api/cursor: context deadline exceeded

**Comment by irridia** [comment]
See #265; 9 minutes is the default client timeout.

**Comment by ajanikow** [comment]
Hello!

You can configure defaultTimeout https://github.com/arangodb/go-driver/blob/master/cluster/cluster.go#L44 or set timeout for context `ctx, c := context.WithTimeout(ctx, 30 * time.Minute)`. 

It will defaults to 9 min.

Best, 
Adam.
