### ISSUE TITLE
Driver support for covering indexes in ArangoDB v3.7?

### ISSUE THREAD

**Issue by sereeena** [arangodb/go-driver#277]
ArangoDB v3.7 has a new View property storedValues, which allows storing document attributes in the View index.
Admittedly this doesn't seem to be discussed much in the documentation, I saw it here:
[https://www.arangodb.com/docs/devel/release-notes-new-features37.html#covering-indexes](url)

The only way I was able to set it properly (in arangosh) is when creating the view:
`db._createView("testView", "arangosearch", {storedValues: [{fields: ["ID", "name"]}]})`

If I attempt to set it via the view properties after the view has been created it doesn't seem to update them.

Anyway I don't see a way of setting this via the v1.1.0 go driver? Will it be added?

It seems like a sensible feature to use, however I  am not sure how well it works as I can't see how to benchmark it. Using EXPLAIN when doing SEARCH on arangodb views never reports using any indexes, only view queries.

Appreciate anyone's comments/experience on the subject!

**Comment by irridia** [comment]
See [#288](https://github.com/arangodb/go-driver/pull/288), github.com/irridia/go-driver@kb-storedValues

**Comment by ajanikow** [comment]
Hello!

Currently we are addressing this issue. It will be applied for Driver V1 and V2.

Best Regards,
Adam.

**Comment by nikita-vanyasin** [comment]
Hello @sereeena @irridia 

The requested feature now is available in `v1.3.0`

Best,
Nikita
