### ISSUE TITLE
Cannot add latest version of driver to go project

### ISSUE THREAD

**Issue by schommi** [arangodb/go-driver#279]
Hey all,

I tried to add the driver to my project as described here: 

https://www.arangodb.com/docs/stable/drivers/go-getting-started.html

```
go get github.com/arangodb/go-driver
```

I'm getting the following error:
```
go: finding github.com/arangodb/go-driver latest
go get: github.com/arangodb/go-driver@v0.0.0-20200821235731-82b41b0cab14 requires
        github.com/arangodb/go-driver/v2@v2.0.0-00010101000000-000000000000: invalid version: unknown revision 000000000000
```` 

I guess, it's not important here, but just to mention: I am using go module support and successfully added modules to my project:

Any ideas on how I can solve the situation? Your help is highly appreciated.

Cheers,
Schommi

**Comment by papey** [comment]
Looks like there is currently some mess with the v2 alpha, I think you can `go get` it with a specific version like

`go get github.com/arangodb/go-driver@1.1.0`

**Comment by schommi** [comment]
> 
> 
> Looks like there is currently some mess with the v2 alpha, I think you can `go get` it with a specific version like
> 
> `go get github.com/arangodb/go-driver@1.1.0`

Thanks for your swift reply. This worked like a charm for me.

**Comment by ajanikow** [comment]
Hello!

We will fix it, however we suggest to use latest stable release.

Best Regards,
Adam.

**Comment by irridia** [comment]
FYI @ajanikow if you create your release tags as the proper semantic tag `v1.1.0`, go modules will automatically pick up your releases rather than pulling master by default. It's difficult for language tools (like go mod) to maintain dependencies without semantic tags == releases.
