### ISSUE TITLE
net/http: request canceled

### ISSUE THREAD

**Issue by marct83** [arangodb/go-driver#28]
Hi. I'm running a local ArangoDB in a docker container and accesing the DB with your code. It appears when I try to run multiple queries in a loop I'm spiratically getting this error:

net/http: request canceled

Sometimes the querys run fine sometimes I get that error. Have you seen this before? Let me know if you need anything else.

**Comment by develf** [comment]
same problem:
If i execute that code: 
`	ctx := context.Background()
	cur, err := db.Query(ctx, "FOR item IN object  RETURN item ", nil)
	if err != nil {
		fmt.Println(err)
		os.Exit(33)
	}
	defer cur.Close()
	fmt.Println(cur)
	os.Exit(99)
`
i receive that:

> net/http: request canceled
> Process finished with exit code 33

If i modify query to:
`cur, err := db.Query(ctx, "FOR item IN object LIMIT 1 RETURN item ", nil)`

i receive that:

> &{{0  [0xc420164360] false} http://login:pass@localhost:8529 0 0xc42012c080 0xc42001c1e0 0 {0 0}}

> Process finished with exit code 99

**Comment by ewoutp** [comment]
This feels like a timeout deep down.
When you do not give a timeout, the system will use a default time. Can you try passing in a context that is configured for a longer (2min or so) timeout?

**Comment by develf** [comment]
You mean something like this?

```
	ctx, cancel := context.WithTimeout(context.Background(), 5000*time.Millisecond)
	defer cancel()

	cur, err := db.Query(ctx, "FOR item IN object RETURN item ", nil)

```

Do not work.

**Comment by ewoutp** [comment]
Can you be precise what does not work?
A timeout of 5 seconds is pretty small, so I would expect timeouts to happen under certain conditions.

**Comment by develf** [comment]
>Can you be precise what does not work?
I can not make any AQL request. I get what I described in my post https://github.com/arangodb/go-driver/issues/28#issuecomment-295692173

>A timeout of 5 seconds is pretty small
While try to query i receive reject less than a second

**Comment by ewoutp** [comment]
I've tried to reproduce, but no luck.
This is the program I tried.

```
package main

import (
	"context"
	"fmt"
	"log"
	"os"

	driver "github.com/arangodb/go-driver"
	"github.com/arangodb/go-driver/http"
)

func main() {
	// Create an HTTP connection to the database
	conn, err := http.NewConnection(http.ConnectionConfig{
		Endpoints: []string{"http://localhost:8529"},
	})
	if err != nil {
		log.Fatalf("Failed to create HTTP connection: %v", err)
	}
	// Create a client
	c, err := driver.NewClient(driver.ClientConfig{
		Connection: conn,
	})
	// Ask the version of the server
	versionInfo, err := c.Version(nil)
	if err != nil {
		log.Fatalf("Failed to get version info: %v", err)
	}
	fmt.Printf("Database has version '%s' and license '%s'\n", versionInfo.Version, versionInfo.License)

	db, err := c.Database(nil, "_system")
	if err != nil {
		log.Fatalf("Failed to open db: %#v", err)
	}

	ctx := context.Background()
	cur, err := db.Query(ctx, "FOR item IN object  RETURN item ", nil)
	if err != nil {
		fmt.Println(err)
		os.Exit(33)
	}
	defer cur.Close()
	fmt.Println(cur)
	os.Exit(99)
}
```

This is the output I get.

```
$ go run query.go
Database has version '3.1.19' and license 'community'
&{{0  [] false} http://localhost:8529 0 0xc4201023e0 0xc420076240 0 {0 0}}
exit status 99
```

(I'm running Arango in a docker container with port mapping 8529 -> 8529)

Does this program work for you? 
If so, what do you need to change in order to make it fail?

**Comment by ewoutp** [comment]
PS. This is using go 1.8

**Comment by develf** [comment]
My go version: 1.7.5

It seems the reason becomes clear.

my db connection code:

```
	conn, err := gohttp.NewConnection(gohttp.ConnectionConfig{
		Endpoints: []string{"http://dbuser:dbpass@localhost:8529"},
	}) 
       ....
       db, err := c.Database(nil, "userdb")
       ....
```

I tried your code and here's what happened:

> you code: with user "root" and db "_system" 
    - works perfect
you code: with user "root" and db "userdb"
    - Failed to get version info: Unexpected status code 401
you code: with user "dbuser" and db "userdb"
    - Failed to get version info: Unexpected status code 401

i comment block "Ask the version of the server" and get this:

> you code: with user "root" and db "_system" 
    - works perfect
you code: with user "root" and db "userdb"
    - net/http: request canceled
you code: with user "dbuser" and db "userdb"
    - net/http: request canceled

With user "root" works perfect. With another user do not work. But another user have right permisiions to his database

**Comment by ewoutp** [comment]
which users have permission to access the following databases?

- _system
- userdb

which ArangoDB version are you using?

**Comment by develf** [comment]
Arango version: 3.1.17

root has permissions to _system and userdb
dbuser has permissions only to userdb

From web interface and from python code user "dbuser" can connect and query to "userdb" without errors

**Comment by ewoutp** [comment]
I've checked and it turns out that it is not allowed to query the database version when you do not have access to the `_system` database.

Now if you leave out the version check and connect to your own `userdb` database, does the sample run ok then?

**Comment by develf** [comment]
> Now if you leave out the version check and connect to your own userdb database, does the sample run ok then?

I already did this and described in the https://github.com/arangodb/go-driver/issues/28#issuecomment-301698296 . Result is "net/http: request canceled".

**Comment by ewoutp** [comment]
Did you set the correct Authentication when creating a client?

As a test, I did the following:

- Start a blank ArangoDB with authentication enabled
- Logged in with root and created:
   - a `userdb` database
   - a `col1` collection in the `userdb` database
   - a `user1` user with password `foo`, granted it rw permission for `userdb`.
 
Then I ran the following test.

```
package main

import (
	"context"
	"fmt"
	"log"
	"os"

	driver "github.com/arangodb/go-driver"
	"github.com/arangodb/go-driver/http"
)

func main() {
	// Create an HTTP connection to the database
	conn, err := http.NewConnection(http.ConnectionConfig{
		Endpoints: []string{"http://localhost:8529"},
	})
	if err != nil {
		log.Fatalf("Failed to create HTTP connection: %v", err)
	}
	// Create a client
	c, err := driver.NewClient(driver.ClientConfig{
		Connection:     conn,
		Authentication: driver.BasicAuthentication("user1", "foo"),
	})
	// Ask the version of the server
	/*versionInfo, err := c.Version(nil)
	if err != nil {
		log.Fatalf("Failed to get version info: %v", err)
	}
	fmt.Printf("Database has version '%s' and license '%s'\n", versionInfo.Version, versionInfo.License)
	*/
	db, err := c.Database(nil, "userdb")
	if err != nil {
		log.Fatalf("Failed to open db: %#v", err)
	}

	ctx := context.Background()
	cur, err := db.Query(ctx, "FOR item IN col1  RETURN item ", nil)
	if err != nil {
		fmt.Printf("Query failed: %#v\n", err)
		os.Exit(33)
	}
	defer cur.Close()
	fmt.Println(cur)
	os.Exit(99)
}
```

This works as expected with exit code 99.
