### ISSUE TITLE
Arangodb Encoding?

### ISSUE THREAD

**Issue by owenmonagan** [arangodb/go-driver#282]
Would it be possible to get an arangodb encoding field?
```
type SomeStruct struct {
	ID   string `json:"id" firestore:"id" arangodb:"_key"`
}
```
In particular, some of my data is not feasible to only be stored in a single data store (arangodb). being able to reuse a struct definition for n data stores would be helpful. Arango, has special fields, and so do others. I would love to be able to reuse the same id field over different datastores.

**Comment by irridia** [comment]
ArangoDB uses the standard JSON Marshaling code, which hard-codes the "json". Fundamentally, Arango would have to support a completely different (and configurable, and parallel) marshaling path for structs. Which seems unpretty.

My best suggestion is to create a mirror struct with different JSON tags, and marshal to the new struct before passing it to Arango. Alternatively you can marshal to a discrete map[string]<foo> with custom keys, and then pass that to Arango and possible get a lower-overhead re-marshal. HIH!

```
type SomeStructForArango struct {
	ID   string `json:"_key"`
}
```
