### ISSUE TITLE
TTL index creation fails when expireAt is 0

### ISSUE THREAD

**Issue by genert** [arangodb/go-driver#291]
According to [documentation](https://www.arangodb.com/docs/3.7/indexing-ttl.html#removing-documents-at-certain-points-in-time), you can set `expireAt` to **0**.

However, when using `EnsureTTLIndex` collection method provided by `go-driver` package: 
```go
_, _, err := col.EnsureTTLIndex(ctx, "expireAt", 0,  &driver.EnsureTTLIndexOptions{})
if err != nil {
    log.Fatal(err)
}
```

It fails with error:
`Failed to create TTL index on collection cache field expireAt TTL 0: expireAfter attribute must be
 a number`

When using any other positive integer instead of 0, the method call succeeds.

**Comment by wolfx** [comment]
Same issue, i think that's because the "omitempty" is set  in the JSON annotation and in this case 0 is a Zero value and then not present in the result of the marshal operation

```go
type indexData struct {
	ID           string   `json:"id,omitempty"`
	Type         string   `json:"type"`
	Fields       []string `json:"fields,omitempty"`
	Unique       *bool    `json:"unique,omitempty"`
	Deduplicate  *bool    `json:"deduplicate,omitempty"`
	Sparse       *bool    `json:"sparse,omitempty"`
	GeoJSON      *bool    `json:"geoJson,omitempty"`
	InBackground *bool    `json:"inBackground,omitempty"`
	Estimates    *bool    `json:"estimates,omitempty"`
	MinLength    int      `json:"minLength,omitempty"`
	ExpireAfter  int      `json:"expireAfter,omitempty"`
	Name         string   `json:"name,omitempty"`
}
```

**Comment by genert** [comment]
@wolfx Correct.

The issue can be solved by changing `ExpireAfter` type to integer pointer instead. This way setting a zero value will work.

**Comment by nikita-vanyasin** [comment]
Hello @genert 

Thanks for feedback.
Unfortunately, fixing this issue with `*int` will break backward compatibility for `driver.Index` interface which now contains `ExpireAfter() int` getter.
Most probably the issue will be fixed in v2 version of go-driver.

Best,
Nikita
