### ISSUE TITLE
Set AllowUserKeys as false does not work

### ISSUE THREAD

**Issue by ednailson** [arangodb/go-driver#295]
The `CreateCollectionOptions` struct has `CollectionKeyOptions` with `AllowUserKeys`. But when you try to set attribute to `false` it does not work because of the struct tag `omitempty`.

**Suggestion:**

```go
type CollectionKeyOptions struct {
	AllowUserKeys bool `json:"allowUserKeys"`
	Type KeyGeneratorType `json:"type,omitempty"`
	Increment int `json:"increment,omitempty"`
	Offset int `json:"offset,omitempty"`
}
```

**Comment by ajanikow** [comment]
Hello!

Will be fixed as part of https://github.com/arangodb/go-driver/pull/300

We could not remove just omitempty - due to fact that would change default actions taken by api. False does not equal empty value.

Also, old structure will be backward compatible.

Best Regards,
Adam Janikowski.

**Comment by ednailson** [comment]
Hello! 

Good job, thanks!
