### ISSUE TITLE
Edge Save: Wrong URL 

### ISSUE THREAD

**Issue by anatse** [arangodb/go-driver#30]
There is an error in function Collection.SaveEdge - used wrong url to store edge in database (HTTP code 404)

There is 
`res, err = col.db.send("edge?collection="+col.Name+"&from="+from+"&to="+to, "", "POST", doc, &doc, &doc) `

But should be 
`res, err = col.db.send("document?collection="+col.Name, "", "POST", doc, &doc, &doc)`

document should be instead edge and additional parameters from, to are redundant

**Comment by ewoutp** [comment]
Which driver are you using?
Does not look like the go driver.
