### ISSUE TITLE
Issues with aborting transactions and preprocessing queries

### ISSUE THREAD

**Issue by shumi12321** [arangodb/go-driver#315]
Hi,
I am having two issues when using ArangoDB and GO drivers:

1. If I abort a transaction and I do not commit it, it seems that GO drivers will not detect from context that db commands are part of transaction so they will be committed on DB. Test `testWithTransactions` creates a transactions, creates some entity, aborts transaction and tries to read entity which should not be in db since transaction containing that command is aborted.
2. It seems that you do some preprocessing on queries so combination of `FOR` statement and ternary operator will result in a way that preprocessing will deduct that ternary operation always succeeds. Ternary operator will not be resolved in run time, but in build time. I found a workaround with using extra `NOT_NULL` in query which is very annoying.

I tried to use latest stable ArangoDB and beta version `3.8-beta.1-3ecde35-47` without success. GO drivers version can be seen in `go.sum` file in attached code (commit `e7a6fa0cbd18`).

Code demonstrating issues:
[arango-issues.zip](https://github.com/arangodb/go-driver/files/6740170/arango-issues.zip)

**Comment by ajanikow** [comment]
Hello!

1) In this test we have flag which specify if entity is present, which is set to false (so we do not expect document):
https://github.com/arangodb/go-driver/blob/master/test/database_transaction_test.go#L148

Based on code:
```go
        c := createClientFromEnv(t, true)
	skipBelowVersion(c, "3.5", t)
	colname := "trx_test_col_abort_2"
	ctx := context.Background()
	db := ensureDatabase(ctx, c, "trx_test", nil, t)
	col := ensureCollection(ctx, db, colname, nil, t)

	t.Logf("Start transaction")
	trxid, err := db.BeginTransaction(ctx, driver.TransactionCollections{Exclusive: []string{colname}}, nil)
	require.NoError(t, err)
	t.Logf("Started transaction %s", trxid)

	tctx := driver.WithTransactionID(ctx, trxid)
	meta1 := insertDocument(tctx, col, t)
	t.Logf("Added document within %s", trxid)

	// document should not exist without transaction
	t.Logf("Check dockument existence outside %s", trxid)
	documentExists(ctx, col, meta1.Key, false, t)

	// document should exist with transaction
	t.Logf("Check dockument existence within %s", trxid)
	documentExists(tctx, col, meta1.Key, true, t)

	// Abort
	t.Logf("Abort %s", trxid)
	err = db.AbortTransaction(ctx, trxid, nil)
	require.NoError(t, err)

	// document should not exist
	t.Logf("Ensure document is missing %s", trxid)
	documentExists(ctx, col, meta1.Key, false, t)

	// document should not exist
	t.Logf("Ensure document is missing %s", trxid)
	documentExists(tctx, col, meta1.Key, false, t)

	// Insert should be not possible
	meta1 = insertDocument(tctx, col, t) // we will get 404
	t.Logf("Added document within %s when it is aborted", trxid)
	```
So it looks perfectly fine - after aborting context (tctx) we get 404 on all requests when this context is used. 

2) Looks more like ArangoDB AQL related issue, Driver just send it to the endpoint using HTTP methods.

Best Regards,
Adam.

**Comment by shumi12321** [comment]
Hi Adam,
Thanks for replying.

For case 1, it appears that I did not know that `db.BeginTransaction` does not append input context. I created a child context by using `driver.WithTransactionID` as in your example and now it works.

For case 2, I will report this bug to another team then.

Thanks,
Josip

**Comment by shumi12321** [comment]
Created a new issue for AQL
