### ISSUE TITLE
WithReturnNew doesn't work with db.Query

### ISSUE THREAD

**Issue by danmia** [arangodb/go-driver#330]
Perhaps this is known/intentional but executing an AQL update via db.Query does not seem to work with WithReturnNew.  The correct documents get updated however I don't seem to get the new documents returned.

```
query := FOR u IN users
               FILTER u.status == "not active" 
               UPDATE u with { status: @status } in users 
               RETURN NEW

	bindvars := map[string]interface{}{
		"status":        "inactive"
	}

	var u []Users
	ctx := context.Background()
	cctx := driver.WithReturnNew(ctx, u)
        // db declared elsewhere
	cursor, ee := db.Query(cctx, query, bindvars)
	
```

It looks like this works outside of the go driver as detailed [here](https://www.arangodb.com/docs/stable/aql/data-queries.html#returning-documents) in the documentation.

Is this a bug, not supported or possibly another way I should be doing this?  The end goal is to just modify multiple documents via an AQL query and have the documents that were changed returned to me.

**Comment by ajanikow** [comment]
Hello!

driver.WithReturnNew wont work in this case, result of query will be in cursor object. It is due to fact that you return `NEW` as a result from your query.

Best Regards,
Adam.

**Comment by danmia** [comment]
should driver.WithReturnNew work if I omit the "RETURN NEW" from the query?  It doesn't seem to.  
I only see examples of driver.WithReturnNew used on document functions in the documentation so maybe that's expected behavior?

**Comment by ajanikow** [comment]
Hello!

It is expected, Query does not return new document by default like Document functions.

**Comment by danmia** [comment]
Thank you for confirming!
