### ISSUE TITLE
Need help in using the go driver

### ISSUE THREAD

**Issue by rkommineni2020** [arangodb/go-driver#339]
Hi All,

I am trying to use the go driver for my day to day operations and the Linux server is not opened to Internet. I could not get the driver using go get github.com/arangodb/go-driver. So I downloaded the code as go-driver-master.zip and transferred it to the server and tried to use it, but i get the below error. It seems it is trying to connect to github.com for any command i try with go. 

hostname: /Users/XXXX/go-driver-master > go list

go: github.com/arangodb/go-velocypack@v0.0.0-20200318135517-5af53c29c67e: invalid version: git fetch -f origin refs/heads/*:refs/heads/* refs/tags/*:refs/tags/* in /Users/rajasekhar_kommineni/go/pkg/mod/cache/vcs/8bf59c4ff87ed0572430602b01720dd6f3f9a47b9aaa788d5aa57867c5544a8f: exit status 128:
	fatal: unable to access 'https://github.com/arangodb/go-velocypack/': Failed connect to github.com:443; Connection timed out
hostname:/Users/XXXXXX/go-driver-master > 

Did anyone faced the issue and is there any workaround on how to use the driver if the server has no connectivity to internet.

Thanks,

**Comment by thijsheijden** [comment]
How are you using the driver? Are you importing it into another go project?

**Comment by jwierzbo** [comment]
No response since 4 months - closing
