### ISSUE TITLE
The big.int field does not work.

### ISSUE THREAD

**Issue by temuera** [arangodb/go-driver#345]
arangodb: 3.8.4e
go:1.7
dataType: big.int

```
	type Story struct {
		K string `json:"_key"`
		A *big.Int
	}

	obj := Story{}
	obj.K = "key"
	obj.A, _ = big.NewInt(0).SetString("280764767231987582253", 10)

	coll.InsertDocument(nil, obj)
	
	coll.ReadDocument(nil, "key1", &obj)

	fmt.Println(obj.K) //output:280764767231987550000

	//in arangoDB web admin interface get: 280764767231987550000 too.
```
It seems that the numerical precision is lost.

**In addition, the scientific notation of json does not work correctly with big.int.**

**Comment by dazhoudotnet** [comment]
more infomation about scientific notation of json:

golang marshal -> save json -> arangodb -> read json -> golang unmarshal

golang big.int -> json with numeric -> arangodb -> json with scientific notation  -> **panic**

does arangodb have a switch to disable scientific notation ?If you use custom datatype for big.int with "marshal unmarshal" will bring more inconvenience.

**Comment by nikita-vanyasin** [comment]
Hello @temuera 

Thanks for feedback. I was able to reproduce the issue.
Unfortunately, it seems impossible to implement on go-driver side because the arangodb returns already-corrupted value because it does not handle big int correctly
https://github.com/arangodb/arangodb/issues/6626

Best,
Nikita
