### ISSUE TITLE
Can't connect because of 'Unsupported content type'?

### ISSUE THREAD

**Issue by allochi** [arangodb/go-driver#35]
Hi,

I'm trying to use ArangoDB for a Go project, when I use the following code on `go version go1.8.3 darwin/amd64` I get the error below. Help is appreciated. 

```go
conn, err := http.NewConnection(http.ConnectionConfig{
		Endpoints: []string{"http://localhost:8529"},
})
if err != nil {
	panic(err)
}

c, err := driver.NewClient(driver.ClientConfig{
	Connection: conn,
})
if err != nil {
	panic(err)
}

db, err := c.Database(nil, "mydatabase")
if err != nil {
	panic(err)
}
```

```bash
panic: Unsupported content type: text/plain; charset=utf-8

goroutine 1 [running]:
main.main()
	/Users/myuser/myprojectpath/myproject/main.go:29 +0x228
exit status 2
```

**Comment by ewoutp** [comment]
Hi, I've tried reproducing this with Go 1.8.3 on the mac, but no luck.
Can you give more information on what setup you're using?

Database version, database settings, anything in between database and driver?
Etc.

Ewout

**Comment by allochi** [comment]
Hi, thanks for your reply

OS: macOS 10.12.5
GO: 1.8.3
ArangoDB: 3.1.21
DB settings: Default

This is my test code

```go
package main

import (
	"fmt"

	driver "github.com/arangodb/go-driver"
	"github.com/arangodb/go-driver/http"
)

func main() {

	conn, err := http.NewConnection(http.ConnectionConfig{
		Endpoints: []string{"http://localhost:8529"},
	})
	if err != nil {
		panic(err)
	}

	c, err := driver.NewClient(driver.ClientConfig{
		Connection: conn,
	})
	if err != nil {
		panic(err)
	}

	db, err := c.Database(nil, "test")
	if err != nil {
		panic(err)
	}

	users, err := db.Collection(nil, "users")
	if err != nil {
		panic(err)
	}

	user := struct {
		Name     string
		Username string
		Title    string
	}{
		"Foo Bar",
		"foobar",
		"Test user",
	}

	meta, err := users.CreateDocument(nil, user)
	if err != nil {
		panic(err)
	}

	fmt.Printf("Created document in collection '%s' in database '%s'\n", users.Name(), db.Name())
	fmt.Printf("%v\n", meta)

}

```

**Comment by ewoutp** [comment]
I've run your program on an ArangoDB local instance (on mac) and docker instance. Both succeed fine.

The error you reported is mostly like originating from here: https://github.com/arangodb/go-driver/blob/master/http/connection.go#L197

Problem is that I do not understand why you get it & what is different is my setup.

Please try the following:

- Add a `c.Version(nil)` call just after creating your client. See if that succeeds.
If it does, I will be surprised.
- Try the following command manually (from console):
```
curl -v http://localhost:8529/_api/version
```
Please post the result here.

**Comment by allochi** [comment]
Hi, thanks for your follow up, the `c.Version(nil)` didn't work, same error, `curl` returned

```
$ curl -v http://localhost:8529/_api/version
*   Trying ::1...
* Connection failed
* connect to ::1 port 8529 failed: Connection refused
*   Trying 127.0.0.1...
* Connected to localhost (127.0.0.1) port 8529 (#0)
> GET /_api/version HTTP/1.1
> Host: localhost:8529
> User-Agent: curl/7.49.0
> Accept: */*
> 
< HTTP/1.1 401 Unauthorized
< X-Content-Type-Options: nosniff
< Www-Authenticate: Bearer token_type="JWT", realm="ArangoDB"
< Server: ArangoDB
< Connection: Keep-Alive
< Content-Type: text/plain; charset=utf-8
< Content-Length: 0
< 
* Connection #0 to host localhost left intact
```

I also reinstalled ArangoDB, same error.

**Comment by ewoutp** [comment]
Can you send the access settings you use for `arangod` and the database you're using?

**Comment by ewoutp** [comment]
Will be properly handled in #38
