### ISSUE TITLE
Support database deletion

### ISSUE THREAD

**Issue by maja42** [arangodb/go-driver#353]
The documentation states:

> Some operations (like deleting a database) cannot easily be done using the API, as they are too dangerous.

I disagree. I'm using ArangoDB with go, and therefore I also need to write unit- and integration-tests for it.
To run integration-tests, I want to setup a new database with a randomly generated name, run all tests in my test-suite and delete the temporary database again afterwards. This allows me to test multiple packages/applications in parallel without name conflicts.

I'm doing this with other external systems as well (Random schema in PostgreSQL, Random vHost in RabbitMQ, random namespace in etcd, ...). But the ArangoDriver does not allow me to do that.
I can't really see why exposing such a function is considered dangerous. I don't need to call it, if I don't want to. And it's absence doesn't protect my database against deletion anyways - there's always the raw HTTP API.

Question:
How can I delete a database in the driver's current state? The documentation says it's not easy - it doesn't say it's impossible.

**Comment by nikita-vanyasin** [comment]
Hello @maja42 

Thanks for your feedback!
I've escalated your concern about documentation to the documentation team.
