### ISSUE TITLE
request support for ArangoDB 3.8

### ISSUE THREAD

**Issue by leemit** [arangodb/go-driver#358]
This project's [README.md](https://github.com/arangodb/go-driver/blob/master/README.md), says ArangoDB 3.7 is currently the highest supported version.  Therefore, I submit this request that arangodb/go-driver be patched to support 3.8 (or update the README.md if it already does).   At [this arangodb.com page](https://www.arangodb.com/download/drivers/), it says this project already supports  ArangoDB 3.8 [ click on the blue GO icon in the white rectangle]

![image](https://user-images.githubusercontent.com/11142058/151592083-617d6c93-e4db-48d5-85de-e8589ea05d85.png)

From the README.md
![image](https://user-images.githubusercontent.com/11142058/151592908-00f507c9-e4d4-444f-8245-7d9528058ad1.png)

**Comment by jwierzbo** [comment]
We will update it as a part of 3.9 release https://arangodb.atlassian.net/browse/TG-230
