### ISSUE TITLE
context WithMergeObjects false merges objects instead of overwriting them

### ISSUE THREAD

**Issue by sbezverk** [arangodb/go-driver#365]
client version 1.2.1 
I create context with WithMergeObjects set to `false`, when I update the object in a collection with `UpdateDocument`, objects are merged instead of being overwritten.

Is it a known issue?

**Comment by nikita-vanyasin** [comment]
Hello @sbezverk 
Please take a look at linked PR #381 for examples on usage of `mergeObjects` option. It works as expected.

Feel free to reopen the issue if you have any questions.
