### ISSUE TITLE
Support for raw string in query return

### ISSUE THREAD

**Issue by MerlinPong** [arangodb/go-driver#37]
Assume the return of AQL query is:

```
[
  "325663",
  "326235",
  "325720",
  "325668",
  "326240",
  "325725"
]
```

My code looking like
```
cursor, _ := myDB.Query(nil, qry, nil)
for {
		meta, err := cursor.ReadDocument(nil, &resd)
		if driver.IsNoMoreDocuments(err) {
			break
		} else if err != nil {
			fmt.Println("for error", err)
		}
		fmt.Printf("Got doc with key '%#v' from query\n", meta)
	}
```

And it returns:
```
for error json: cannot unmarshal object into Go value of type []string
```

For example, JAVA driver for arango supports input a class(e.g ```String.class```) as parameters in the query method. And that will solve this issue.

**Comment by ewoutp** [comment]
In the test-set we have tests for queries just like that. Difference is that they take 1 string at a time (in `ReadDocument`).
Are you trying to read all strings at once in an array?

**Comment by MerlinPong** [comment]
@ewoutp 
Exactly. I found a solution for this situation.

I modified the AQL and make the result as a JSON like:
```
[
  {
    "Result": [
      "482635",
      "482640"
    ]
  }
]
```

And I define a type like:

```
type resDoc struct {
		Result []string `json:"Result"`
	}

meta, err := cursor.ReadDocument(nil, &res)
```

Anyway, it's good have return as **raw string** type, so that the structure of return will be flexible.

**Comment by ewoutp** [comment]
Ok good.
The alternative would be something like this (when still returning strings from the AQL query):
```
var myString string 
meta, err := cursor.ReadDocument(nil, &myString)
```
