### ISSUE TITLE
getting eof error while connecting to https://server if ssl is disabled in server

### ISSUE THREAD

**Issue by pritamlipu1** [arangodb/go-driver#372]
Note: arangodb server is not ssl enabled. 
There are 2 issues I found when I tried to connect with https:// in ssl disabled arangodb server.

1. when I am trying to connect arangodb server with https, its giving EOF error. Error should have been thrown in better way.
when calling _, err := client.DatabaseExists(ctx, name)
its giving eof error, which can be better so that we can handle it in a better way.
error: "error: Get "https://localhost:8529/_db/profilerdb/_api/database/current": EOF"

2. It did not throw error while calling newconnection function.
eg: conn, err := http.NewConnection(http.ConnectionConfig{
		Endpoints:"https://server_ip:8529",
		TLSConfig: &tls.Config{
			InsecureSkipVerify: true,
		},
	})
Here err was nil.
Please comment.

**Comment by ajanikow** [comment]
Hello!

This error is from go library which is used behind. We can't tell if your connection failed due to missing tls connection, failure on network level, restart of server or proxy - all above can cause this generic error.

Best Regards,
Adam.

**Comment by nikita-vanyasin** [comment]
Closing.
@pritamlipu1 feel free to reopen if you still have any questions.

**Comment by pritamlipu1** [comment]
@ajanikow @nikita-vanyasin I am using this go package to connect to arangodb. And If I try to access with https to a ssl disabled server, then I am getting error: "error: Get "https://localhost:8529/_db/profilerdb/_api/database/current": EOF".
What I am saying is We can have a better error/error code so that in code we will know ok its ssl disabled and lets try with "http://localhost:8529".
Workaround - If I get EOF in error, then I am trying to reconnect through "http://"

Environment: there are 2 clusters. 1 is dev and another one is prod..prod is ssl enabled but dev is ssl disabled and it was breaking in dev env. So I had a workaround.

I hope I explained it very well..

Thanks

**Comment by pritamlipu1** [comment]
@ajanikow  @nikita-vanyasin plz comment

**Comment by pritamlipu1** [comment]
@jwierzbo Please help here. I have a workaround to this issue. But its better to have proper error from this package.

**Comment by jwierzbo** [comment]
@pritamlipu1 Unfortunately this EOF response comes from the library which we use in go-driver (as mentioned by @ajanikow) and we can not change this behaviour.
