### ISSUE TITLE
cursor.ExecutionTime() float to int looses resolution

### ISSUE THREAD

**Issue by xpegenaute** [arangodb/go-driver#373]
Hi all!,

first of all thanks for your time and effort. My details are as follows:
* ArangoDB version: 3.7.13 CE
* Arango driver version: 1.2.1
* Platform: Docker

I am trying to monitor the performance of the queries. Not only I want to monitor my code, I want to compare them with the ones reported by Arango. For this, I am using the cursor.Statistics(): it provides the [ExecutionTime function](https://github.com/arangodb/go-driver/blob/e985a4b0e7aadd44a3835427475cf3fc49a9c084/cursor_impl.go#L314) and I am having the problem that it always reports a duration of "0".

Looking at the code, apparently it happens because "cs.ExecutionTimeInt" which is float64 is casted to int() when calling time.Duration(), therefore all the decimal part disappears and its always zero for queries below a second.

Am I right ?, if that's right is it possible to have a quick fix ?, I tried to make a PR but it is not clear in your doc the units reported by ExecutionTimeInt, it could be dependent of the relaying OS.

Regards,
Xavi

**Comment by jwierzbo** [comment]
We are going to fix it soon: https://arangodb.atlassian.net/browse/TG-229
