### ISSUE TITLE
Creating custom analyzer in `CreateSearchView` by defining the analyzer in `driver.ArangoSearchElementProperties`

### ISSUE THREAD

**Issue by aaqibb13** [arangodb/go-driver#392]
- I'm trying my hands on custom analyzers for text processing. For reference,[State-of-the-art-preprocessing-and-filtering-with-arangosearch](https://www.arangodb.com/2020/12/state-of-the-art-preprocessing-and-filtering-with-arangosearch/) is an excellent resource to emphasize on text-processing capabilities of arangosearch with custom analyzers.
- I've tried by defining my analyzer in [driver.ArangoSearchElementProperties](https://github.com/arangodb/go-driver/blob/bb796bab71c55d7d7864e18104875901448d482e/view_arangosearch.go#L380) itself. I've tried it in the following way:
```go
viewName, err := db.CreateArangoSearchView(ctx, myViewName, &driver.ArangoSearchViewProperties{
Links: driver.ArangoSearchLinks{
	collectionName: driver.ArangoSearchElementProperties{
		AnalyzerDefinitions: []driver.ArangoSearchAnalyzerDefinition{
			{
				Name: "custom_analyzer",
				Type: driver.ArangoSearchAnalyzerTypePipeline,
				Properties: driver.ArangoSearchAnalyzerProperties{
					Locale: "en_US.utf-8",
					Pipeline: []driver.ArangoSearchAnalyzerPipeline{
						{
							Type: driver.ArangoSearchAnalyzerTypeNorm,
							Properties: driver.ArangoSearchAnalyzerProperties{
								Locale: "en_US.utf-8",
							},
						},
						{
							Type: driver.ArangoSearchAnalyzerTypeNGram,
							Properties: driver.ArangoSearchAnalyzerProperties{
								Min:              utils.NewInt64(1),
								Max:              utils.NewInt64(14),
								PreserveOriginal: utils.NewBool(false),
							},
						},
					},
				},
			},
		},
		Fields: map[string]driver.ArangoSearchElementProperties{
			"businessName": {
				Analyzers: []string{
					"text_en",
				},
			},
			"locationName": {
				Analyzers: []string{
					"text_en",
				},
			},
		},
	},
},
	})
	if err != nil {
		log.Println("error creating view: ", err)
	}
```
- Do I need to add my `custom_analyzer` in `Fields` like:
```go
Fields: map[string]driver.ArangoSearchElementProperties{
			"businessName": {
				Analyzers: []string{
					"text_en",
                                       "custom_analyzer",
				},
			},
			"locationName": {
				Analyzers: []string{
					"text_en",
                                       "custom_analyzer",
				},
			},
		},
```
or the underlying analyzer that I'm using, like `norm` and `ngram` for instance.
-  What I want to achieve is to create a `pipeline` type analyzer with underlying `norm` and `ngram` analyzers. What I'm trying to achieve is this:

```js
analyzers.save(
  'bigram', 
  'pipeline', 
  { 
    pipeline: [ 
      { type:'norm',  properties: { locale:'en', case:'lower'} }, 
      { type:'ngram', properties: { min:2, max:2, preserveOriginal: false, streamType:'utf8' } }
    ]
  }, 
  ["frequency","norm","position"]);
```
> As a side note: I did look at #318 and tried to find a work around `database_arangosearch_analyzers_impl.go`. I'd love any help in this regard. 
@maierlars to the rescue, maybe? ;)

**Comment by jwierzbo** [comment]
I've prepared E2E test to implement above arangsh code:
https://github.com/arangodb/go-driver/pull/394/files

Let me know if now it is clear for you :)

**Comment by aaqibb13** [comment]
@jwierzbo Thanks. I was able to create my SearchView with my created analyzer! 👍🏼
