### ISSUE TITLE
Collection Properties cannot unmarshal field .lastValue of type int64

### ISSUE THREAD

**Issue by joosep-wm** [arangodb/go-driver#400]
When calling `Properties(ctx context.Context) (CollectionProperties, error)` I get the error with the cause:

`Cause: json: cannot unmarshal number 9926818832808110302 into Go struct field .lastValue of type int64`

Seems the issue comes from the fact that last value is a 20 digit number, but int64 holds only 19 digits. Using uint64 instead would solve the issue.
This happens only when the "last value key" is so large number.

Using version 1.3.2.
Commit hash: b74bb426feda2f812dbcc7c3d899dd0c4c7a855c
go version go1.18.2 darwin/amd64
Startup mode: daemon

**Comment by jwierzbo** [comment]
Fixed is available if the latest version
