### ISSUE TITLE
Add `yaml` tags to `CreateCollectionOptions`

### ISSUE THREAD

**Issue by kushuh** [arangodb/go-driver#402]
I love the fact that `CreateCollectionOptions` includes json tags (most db package I use don't bother to even include them on their configuration objects). Unfortunately I use `yaml` files to load my configuration, is it possible to include them as well ?

```go
type CreateCollectionOptions struct {
    CacheEnabled         *bool  `json:"cacheEnabled,omitempty" yaml:"cacheEnabled,omitempty"`
    DistributeShardsLike string `json:"distributeShardsLike,omitempty" yaml:"distributeShardsLike,omitempty"`

    // ...
}
```

I was thinking of forking the configuration object and adding the tags myself, but since the object is pretty large and has subfield with custom types, I believe it could benefit to include yaml tags directly in the package itself.

Using version 1.3.2
Go version 1.18.3

**Comment by jwierzbo** [comment]
We are not planning to add `yaml` tag.

IMHO you're doing it right - you should keep it separated into different layers (database, app API, app configuration).
