### ISSUE TITLE
If I want to create a database, should I always use the root user?

### ISSUE THREAD

**Issue by curiosport** [arangodb/go-driver#407]
In short, I have this code that works:

```
...
client, err := driver.NewClient(driver.ClientConfig{
	Connection:     conn,
	Authentication: driver.BasicAuthentication("root", "somePassword"),
})

cred := driver.CreateDatabaseUserOptions{
	UserName: "otherUser",
	Password: "onotherPassword",
}

opts := &driver.CreateDatabaseOptions{
	Users: []driver.CreateDatabaseUserOptions{cred},
}

_, err = client.CreateDatabase(nil, "sampledb", opts)
if err != nil {
	panic(fmt.Sprintf("Failed to create database: %s", err))
}
```

But when I change the credentials to the following:
```
client, err := driver.NewClient(driver.ClientConfig{
	Connection:     conn,
	Authentication: driver.BasicAuthentication("otherUser", "anotherPassword"),
})
```

I get this error:
`panic: Failed to create database: not authorized to execute this request`

I thought that when I created a user (in this case "otherUser") that user could also create database, but with ArangoDB it seems that this is not the case, I tried to make `arangod` start the server with "otherUser" but seeing that there was no option available my deduction is that ArangoDB only allows database creation with the user root, is that correct or am I missing something?

If not, could you please tell me how to make **otherUser** also able to create a database?

**Comment by curiosport** [comment]
[https://www.arangodb.com/docs/stable/data-modeling-databases-working-with.html](https://www.arangodb.com/docs/stable/data-modeling-databases-working-with.html)

Reading this in the documentation: "This method can only be used from the _system database".

I logged into arangosh and ran the following:
```
var users = require("@arangodb/users");
users.grantDatabase("otherUser", "_system", "rw");
```

So now my code with the credentials of the **otherUser** is working.

**Comment by jwierzbo** [comment]
@curiosport the same can be done with go-driver and `SetDatabaseAccess` method:
https://github.com/arangodb/go-driver/blob/dedffd08e4faf7de0b9c8a5f2b0685a69bc5c97f/user.go#L56-L59
