### ISSUE TITLE
Ensure***Index are unclear ?

### ISSUE THREAD

**Issue by benjish** [arangodb/go-driver#409]
Hi,

Where is the documentation about "Hash Indexes", "Skiplist Indexes", what is the difference with "Persistent Indexes"?
I can't find anything that explains the difference

In the GUI, it is written that all three are equivalent, but :
- Why is there no "driver.EnsurePersistentIndexOptions.NoDeduplicate"?
- Why are there 3 types of indexes if they do the same thing?

Unless I am mistaken, driver.Ensure***IndexOptions.Estimates bugs,
I tested with EnsurePersistentIndex, EnsureHashIndex and EnsureSkipListIndex with the same result

```go
var falseV = false
_, _, err := col.EnsurePersistentIndex(ctx, []string{"email"}, &driver.EnsurePersistentIndexOptions{
  Name: "email_index",
  Unique: true,
  Sparse: false,
  Estimates: &falseV,
})
```

create an index with "deduplicate: true, estimates: true" extras

**Comment by curiosport** [comment]
It is not a complete answer but it is something:
[https://www.arangodb.com/docs/stable/indexing-which-index.html](https://www.arangodb.com/docs/stable/indexing-which-index.html)

**Comment by benjish** [comment]
I had obviously read this before. But there's nothing about hash indexes or skiplist indexes

**Comment by benjish** [comment]
I had obviously read this before. But there's nothing about hash indexes or skiplist indexes

**Comment by jwierzbo** [comment]
@curiosport "hash" and "skiplist" are only aliases for "persistent" with the RocksDB storage engine.
Since RocksDB is our only storage engine since 3.7, there is no real difference.

Missing field for PersistentIndex has been added as well

**Comment by benjish** [comment]
Good responsiveness!

What about "Estimates" fields?
I don't know if this is an important feature, but it doesn't seem to work

**Comment by jwierzbo** [comment]
`Estimates` is the feature enabled by default. Using go-driver you can disable it.
Here is more information about it: https://www.arangodb.com/docs/3.9/release-notes-new-features38.html#optional-selectivity-estimates-for-new-indexes
