### ISSUE TITLE
user with limited access rights: client.Database error EOF 

### ISSUE THREAD

**Issue by andmn** [arangodb/go-driver#442]
I created a database user with password and limited access rights:
- database mydb => Access
- collection myCol1 => Read only
- collection myCol2 => No access

When I try to connect with client.Database it return EOF, manual call of the request (client_database_impl.go:34)
http://mydbhost:8529/_db/mydb/_api/database/current
=> {"error":true,"errorNum":11,"errorMessage":"not authorized to execute this request","code":401}

Another question: should a connect really create a new database, see client_database_impl.go:31 and client_database_impl.go:45?

ArangoDB web ui: login and queries are usable a expected.

Version: github.com/arangodb/go-driver v1.3.3

**Comment by andmn** [comment]
Debug session results:

- the user access rights are not the root cause
- mydbhost had no ssl enabled, all other run with ssl enabled

root cause is the ssl handling from the driver, vst.ConnectionConfig has set tls.Config{ InsecureSkipVerify: true, } and
* url vst://mydbhost => EOF
* url vst+ssl://mydbhost => EOF
* url http://mydbhost => connected
* url https://mydbhost => EOF

I assume vst://mydbhost should work as http://mydbhost

**Comment by jwierzbo** [comment]
I'm not able reproduce this case.

Here is the sample code which I've used in my tests and which is working:
```
       config := http.ConnectionConfig{
		Endpoints:   []string{"http://localhost:7001"},
		TLSConfig:   &tls.Config{InsecureSkipVerify: true},
		ContentType: driver.ContentTypeJSON,
	}
	conn, err := http.NewConnection(config)
	client, err := driver.NewClient(driver.ClientConfig{
		Connection:     conn,
		Authentication: createAuthenticationFromEnv(t),
	})

       configVST := vst.ConnectionConfig{
		Endpoints: []string{"http://localhost:7001"},
		TLSConfig: &tls.Config{InsecureSkipVerify: true},
		Transport: protocol.TransportConfig{
			Version: protocol.Version1_1,
		},
	}
	connVST, err := vst.NewConnection(configVST)
	clientVST, err := driver.NewClient(driver.ClientConfig{
		Connection:     connVST,
		Authentication: createAuthenticationFromEnv(t),
	})
```

With above code I can manage ArangoDB data using both clients - `client` and `clientVST`
