### ISSUE TITLE
Use case to re-enable Velocypack encoding for _api/gharial

### ISSUE THREAD

**Issue by nashikb** [arangodb/go-driver#480]
We currently have a use case where we would like to keep our unique identifiers in an `id` field in our API requests, but have that field store into the `_key` field in ArangoDB.

I'd like to accomplish this with the `velocypack` struct tags, as follows in this Go example:
```
type ExampleEntity struct {
  ID    string  `json:"id,omitempty" velocypack:"_key"`
  Name  string  `json:"name,omitempty"`
}
```

In this way, incoming API requests using the `id` field are marshaled correctly, and when the ExampleEntity is sent to ArangoDB (via for example AQL) this differential marshaling works perfectly.

In the API case, it seems like I need to explicitly pass `ContentType: driver.ContentTypeVelocypack` to `go-driver.http.NewConnection()`. But AQL seems to default to `velocypack`.

However, [there's a six year old change](https://github.com/arangodb/go-driver/pull/29/files#diff-e5d1ccba5f52701b547d6530b3c58592d298d245e7840fb455f13c896bb5a28fR128) that silently disables `velocypack` encoding for the API (even when it's specified over the default JSON), which creates a situation where AQL and the API differ in implementation, providing silent (and obviously significant) data consistency issues:

```
	ct := c.contentType
	if ct != driver.ContentTypeJSON && strings.Contains(path, "_api/gharial") {
		// Currently (3.1.18) calls to this API do not work well with vpack.
		ct = driver.ContentTypeJSON
	}
```

Given that the comment references ArangoDB 3.1.18, I suspect many things have changed since then. Anecdotally, my testing with a fork of `go-driver` with the logic above removed (see PR#481) works fine on 3.10.x, and calls like `CreateDocument()` behave consistently with `Query("INSERT")`.

Can the utilization of `velocypack` in this context be validated or fixed, and this ability re-enabled? Alternatively, could an override be added to this safety net (maybe `driver.WithForceVelockpack(ctx)`) so we don't have to maintain a fork? :-)

This differential behavior seems fraught (though to be fair, I'm not sure many people lean on `velocypack` for the API), but it's also an extremely useful method of transparently passing keys to the `_key` value without having `_key` specified in our APIs (not gRPC friendly), or a massive amount of field-copying before and after the Unmarshal/Marshaling phases.

Thanks!

@ewoutp

**Comment by jwierzbo** [comment]
I guess we can add that change, but first we need to test it well. I will add it to our todo for this or next release/

**Comment by jwierzbo** [comment]
It is in the master already (https://github.com/arangodb/go-driver/pull/512) and will be part of the next go-driver release once 3.11 of ArangoDB will be officially released.
