### ISSUE TITLE
Add a Ping() method

### ISSUE THREAD

**Issue by charlyjna** [arangodb/go-driver#482]
Hi, there is no Ping() method to check if connection with database is still working.
I am working on a project using ArangoDB to store production data and having a Ping() method like in other DB driver could be very helpful to preempt connection loss.

Something like:  `func (c *driver.Connection) Ping() error { }`

**Comment by nashikb** [comment]
FWIW: when creating a persistent data layer service for ArangoDB, I load the database and graph at service instantiation time. This of course validates that the ArangoDB connection details are configured properly and that the database is up. If a service only dynamically loads databases and graphs, then Version() could be useful for this purpose.

Also, there's no need to preempt connection loss, as there are no persistent connections, per se. The driver handles connects and reconnects well, in my experience.
