### ISSUE TITLE
Use cases to expose getters for Context values

### ISSUE THREAD

**Issue by nashikb** [arangodb/go-driver#485]
### Proposal

Currently, `go-driver` stores various request configuration information as `ContextKey`s on passed-in `Context`s. Examples include passing a transaction ID (e.g., `driver.WithTransactionID(ctx, txnID)`) or the `WithReturnOld()` and `WithReturnNew()` mechanisms. The context keys themselves are private in `context.go`, e.g.:
```
	keyReturnNew                ContextKey = "arangodb-returnNew"
	keyReturnOld                ContextKey = "arangodb-returnOld"
	keyTransactionID            ContextKey = "arangodb-transactionID"
```

As the values applied to `Context`s are private, I'd like to propose adding getters. For example, `HasTransactionID()`, or `GetTransactionID()`. For example:
```
func GetTransactionID(parent context.Context) TransactionID {
	ctxTxnID, ok := contextOrBackground(parent).Value(keyTransactionID).(TransactionID)
	if !ok {
		return TransactionID("")
	}
	return ctxTxnID
}
```

### Use cases

The reason I'm proposing this addition is that I've had two use cases to inspect these.

The first is part of unit testing using mocks of go-driver. In order to test `ReturnOld`/`ReturnNew` operations, one has to set these return values as part of the mock. Here's an example of how I believe this has to work, currently (and I've been using successfully for a couple of years now):
```
        entity := &models.Entity{
            ID: "1234",
            Name: "Name",
        }
	mockColl := &arangomocks.Collection{}
	s.mockGraph.On("VertexCollection", mock.Anything, collections.Entity.String()).
		Return(mockColl, nil)
	s.mockDatabase.On("BeginTransaction", mock.Anything, mock.Anything, mock.Anything).
		Return(driver.TransactionID("myTransactionID"), nil)
	mockColl.On("CreateDocument", mock.Anything, entity).
		Run(func(args mock.Arguments) {
			newEntity := args[0].(context.Context).Value(driver.ContextKey("arangodb-returnNew")).(*models.Entity)
			newEntity.ID = "1234"
                        newEntity.Name = "New Name"
		}).
		Return(driver.DocumentMeta{}, nil)
```
The key part here being: `.Value(driver.ContextKey("arangodb-returnNew")).(*models.Entity)`

In this case, I have to copy and paste the private value of `driver.keyReturnNew` in order for this to work. Even for testing, I'd obviously rather not rely on the value of the private `const`.

The other use case is for wrapping ArangoDB transactions with panic recovery. I use helper functions to implement this pattern:
```
    txnID, _ := handler.db.BeginTransaction(ctx, ...)
    defer handler.abort(ctx, &txnID)
    // ...
    handler.commit(ctx, &txnID)
```
If I were able to "publicly" inspect the TransactionID within the Context, separately tracking and passing in the transaction ID would not be necessary. I'd also argue that inspecting the Context for the transaction ID is a more reliable, single-source-of-truth method for tracking transaction IDs.

I could see two approaches here, depending on the preferences of the maintainers:
1. Add getters to all ContextKeys (aka everything with a `With...()` function)
2. Add getters to ContextKeys that "feel safe" to expose, e.g., TransactionID, ReturnOld, ReturnNew.

I'd be happy to contribute these changes if it feels useful to the codebase.

Thanks!

Slightly OT: What is the current plan for v2 in terms of architectural changes? In other words, is there a WIP where a change like this would need to be ported forward, or does v2 rework this mechanism, etc?

**Comment by jwierzbo** [comment]
We will add `HasTransactionID`

**Comment by jwierzbo** [comment]
@nashikb In V2 we try to avoid using those Context approaches and instead we use optional args:
https://github.com/arangodb/go-driver/blob/master/v2/arangodb/collection_documents_update.go#L86-L91
