### ISSUE TITLE
Question: how to write auto-inc feild?

### ISSUE THREAD

**Issue by zgr126** [arangodb/go-driver#51]
That is the best way to achieve auto-inc feild like userid ?

type User struct {
  Id int64
  Name string
  ...
}

**Comment by zgr126** [comment]
I fond driver.CreateCollectionOptions. sorry, I missed it, But should I use it? 
It use _key to be auto-inc primary key means that I should definition

Id    string    `json:",omitempty"`

but INSERT ignor it and QUERY make User.Id = meta.Key ?
I feel strange :joy::joy:
some achieve better?

**Comment by ewoutp** [comment]
Arango will always include 3 fields in your documents:
- `_key` Unique (collection specific) key 
- `_id` Combination of collection + `_key`
- `_rev` Revision of the document 

The go driver returns these fields as meta data, so there is no need (but it is allowed) to include these fields in your go structure.

You can use the `_key` (or `_id`) as a unique user-id. Arangod itself will ensure uniqueness.
If you want a custom id, add an index on that field with the unique constraints turned on. You will have to create the values by yourself.
