### ISSUE TITLE
401 and 503 for not leader for different request

### ISSUE THREAD

**Issue by onikcode** [arangodb/go-driver#536]
i am a little confused in working of arango db and driver.
i have installed a cluster with two nodes: arango-1 and arango-2. Arangodb 3.9.9
Assume that the leader is second
I make requests to first one (not leader):
1) 
`curl 'http://arangodb-1/_db/my_lovely_db_name/_api/collection/my_lovely_collection' --header 'Authorization: Basic MGIxMDVl=' --header 'x-arango-driver: go-driver-v1/1.6.0'`
and have response:
`{"error":true,"errorNum":11,"errorMessage":"forbidden","code":401}`
2)
`curl 'http://arangodb-1/_db/my_lovely_db_name/_api/database/current' --header 'Authorization: Basic MGIxMDVl=' --header 'x-arango-driver: go-driver-v1/1.6.0'`
and response:
`{"error":true,"errorNum":1496,"errorMessage":"not a leader","code":503}`

in the driver we work in method
https://github.com/arangodb/go-driver/blob/eda9ddfc1920bef842645703c2559ceeb2da692d/cluster/cluster.go#L107

in case of request 2) I would get inside 'err == nil && resp.StatusCode() == 503' and it would have ended with server = c.getNextServer(). second round and we reach leader node.
in case of request 1) I get error unauthorized and that all.

Is it ok that not leader answers different for 'get' requests?
Do i need to add additional requests in code to check that the node still leader.
Please help with understanding 

(UPD: sorry, made a mistake in 2) request. have corrected. both requests to not leader)

**Comment by jwierzbo** [comment]
By cluster setup you mean Cluster mode with DBservers, Coordinators and Agents or Single Failover Mode with Leaders and followers?

**Comment by dyakovni** [comment]
@jwierzbo 
I mean the Single Failover Mode with Leaders and followers

**Comment by dyakovni** [comment]
@jwierzbo 
>Once the leader has changed (503 error) look again for the new endpoint and retry your request
Right, and we have this logic in the mentioned https://github.com/arangodb/go-driver/blob/eda9ddfc1920bef842645703c2559ceeb2da692d/cluster/cluster.go#L107
and it would work if not the unexpected 401 status for `_api/collection/*` endpoint

**Comment by jwierzbo** [comment]
Why 401 is unexptected? The 503 comes from non-leader, 401 comes from the leader...
