### ISSUE TITLE
bulk import API

### ISSUE THREAD

**Issue by TianDaGe** [arangodb/go-driver#55]
[https://docs.arangodb.com/3.2/HTTP/BulkImports/](url)
How can I use BulkImport feature in arangodb/go-driver?

**Comment by ewoutp** [comment]
The bulk import API is currently not supported in the go driver.

What you can (and probably want to) use in the multi-document API. Look for `CreateDocuments` on a `Collection`.

**Comment by naulacambra** [comment]
Any option this feature would be supported any time soon?
