### ISSUE TITLE
which type should be injected ? 

### ISSUE THREAD

**Issue by muhammad-davatgar** [arangodb/go-driver#554]
hello , i am using dependency injection to inject arango connection to my handlers and i was wondering which type i should inject, `driver.Client` or `driver.Database` ? 
i first thought `driver.Database` would have better performance since opening database would be already done in the time of querying , but i then wondered if using this object disrupts with the functionality of connection pool?

**Comment by jwierzbo** [comment]
You can use `driver.Database` since it uses `driver.Client` underneath.
