### ISSUE TITLE
Why Drop Collection Doesn't Exists

### ISSUE THREAD

**Issue by sh0umik** [arangodb/go-driver#632]
I am using Arangodb for a SaaS project of mine. As you might guess, based on user requests, it creates a few collections, and if the user decides, we allow the user to remove it. the DropCollection method doesnt exists on golang sdk. Is there any reason why ? 

I can see it does in `arangojs`, so why not here ? Is this a design choice or lack of time ? Same for V2 of this sdk.

https://arangodb.github.io/arangojs/8.2.1/interfaces/collection.DocumentCollection.html#drop

**Comment by jwierzbo** [comment]
@sh0umik we do have them for both V1 and V2 implemented:
https://github.com/arangodb/go-driver/blob/f3dfc4ba681a40cff825cfa4d440b58983f15b6b/v2/arangodb/collection.go#L36-L36
