### ISSUE TITLE
docs.arangodb.com instructions not in line with the latest version (v2.1.2?)

### ISSUE THREAD

**Issue by tomaszandrzej** [arangodb/go-driver#636]
The instructions at https://docs.arangodb.com/3.11/develop/drivers/go/#connect-to-arangodb require the latest version from the master branch (possibly v2.1.2), which has not yet been tagged. The connection_configuration.go file, containing DefaultHTTP2ConfigurationWrapper, is not included in the latest tagged version (v2.1.1).

**Comment by jwierzbo** [comment]
@tomaszandrzej FYI: https://github.com/arangodb/go-driver/releases/tag/v2.1.2 has been released
