### ISSUE TITLE
Delay between permissions change and check

### ISSUE THREAD

**Issue by neunhoef** [arangodb/go-driver#67]
Permissions between coordinators are only eventually consistent. In https://github.com/arangodb/go-driver/blob/master/test/user_auth_test.go we should add a delay of 3s between changing some permissions or user settings and checking them, for the case that a different coordinator is being used for the check.

**Comment by ewoutp** [comment]
Updated the timeout to 5sec but still no luck

**Comment by nikita-vanyasin** [comment]
Closing: this code was updated to retry each two seconds but no more than 1 minute in total.
https://github.com/arangodb/go-driver/blob/master/test/user_auth_test.go#L274
