### ISSUE TITLE
Revalidate whether workaround can be removed

### ISSUE THREAD

**Issue by dothebart** [arangodb/go-driver#68]
We retested 
https://github.com/arangodb/arangodb/issues/2439
with the java driver and the behaviour could not be reproduced. Thus this ticket will be closed now. 
Please revalidate whether the workaround can be removed from the go driver, and if not reopen the issue.

**Comment by ewoutp** [comment]
We cannot remove the workaround from the go-driver since the driver also has to remain working with older versions.
Closing this issue
