### ISSUE TITLE
Add non-context version of method calls

### ISSUE THREAD

**Issue by starJammer** [arangodb/go-driver#7]
I should be able to do this and submit a PR but I wanted feedback first. I don't know if it's common to provide both a non context version of methods as well as a context version.

From my point of view it is similar to the idea of "program synchronous method calls and callers can worry about adding concurrency, but making a concurrent method synchronous is not always easy and complicates the methods". 

I would still keep the context versions in this case and they would delegate to the non-context versions.

Any feedback? 

FYI, haven't looked at the code yet, just the README and the interface definitions.

**Comment by ewoutp** [comment]
In any call you can pass `nil` for the context argument.

Will there still be a need for non-context method calls then?

**Comment by ewoutp** [comment]
Closing this issue since the context arguments are an essential part of the API design and you're allowed to pass `nil` in all cases.
