### ISSUE TITLE
correct way to get multiple documents ?

### ISSUE THREAD

**Issue by stefanwuthrich** [arangodb/go-driver#70]
I try to do something like this:

`
query := "FOR d IN scenario RETURN d"
	cursor, err := storage.ArangoDb.Query(storage.Ctx, query, nil)

	if err != nil {
		fmt.Println(err)
	}

	var scenarios []Scenario
	_, err = cursor.ReadDocument(storage.Ctx, &scenarios)
`

which of course gives following error:
cannot unmarshal object into Go value of type []model.Scenario
as cursor.ReadDocument get's only 1 document.

What is the correct way to get full array?

**Comment by ewoutp** [comment]
@stefanwuthrich You should iterate over the cursor for every document.
 See https://github.com/arangodb/go-driver#querying-documents-one-document-at-a-time

Note. This driver will internally fetch multiple documents at a time.
