### ISSUE TITLE
Is there an ArangoDB-Object on Struct?

### ISSUE THREAD

**Issue by Fruchtgummi** [arangodb/go-driver#75]
How do I get _key, _rev, _id and very important the lastkey (lastid) from Arango?

```
type mystruct struc {
   arangodb.document
  .....
or

  _key
  _lastkey
   ....
}

```

**Comment by ewoutp** [comment]
@Fruchtgummi all functions that modify a document return a `DocumentMeta` object.
That object contains the key, rev & ID field. No need to put that in your document structure (allthough you're allowed to do so)

See https://godoc.org/github.com/arangodb/go-driver#CollectionDocuments

**Comment by ewoutp** [comment]
Humm. missed the lastkey part, checking...

**Comment by ewoutp** [comment]
I've checked. When replacing or updating documents, there is also a `_oldRev` field. This field is not directly exposed in the go-driver API, but if can probably get it as follows:

The go driver has a `WithReturnOld` function that configures a context to return the old document after an update/replace operation. 

```
type YourDocumentType struct {
    Rev string `json:"_rev"`
}
var oldDoc YourDocumentType
ctx := driver.WithReturnOld(context.Background(), &oldDoc)
_, err := collection.ReplaceDocument(ctx, key, newDocument)
if err == nil {
   // Now oldDoc.Rev contains the revision of the document before it was replaced
```

Hope that answers your question.
