### ISSUE TITLE
Cursor returned from a query with empty Count

### ISSUE THREAD

**Issue by vanobig** [arangodb/go-driver#82]
**AQL query**
`FOR c IN commit 
  FILTER c.company_id == @company_id 
    AND c.date >= DATE_TIMESTAMP(@start_date) AND c.date <= DATE_TIMESTAMP(@end_date) 
  LET files = LENGTH(c.files) > 0 ? c.files : [] 
  FOR f IN files COLLECT extensions = f.type 
    RETURN extensions`

**Details**
Query returns a non-empty result. However, the Cursor returned from a query has Count = 0
See the screenshot enclosed.

![screen shot 2018-01-04 at 11 47 12 am](https://user-images.githubusercontent.com/5801713/34581389-1291f7bc-f145-11e7-98b4-e6e471c855b8.png)

**Comment by ewoutp** [comment]
Did you create the cursor with a context prepared with `WithQueryCount`?

**Comment by vanobig** [comment]
Oh, this is a very good question @ewoutp. I have completely missed that from the documentation.
My bad for sure.
