### ISSUE TITLE
Multi-tenancy connection management

### ISSUE THREAD

**Issue by vanobig** [arangodb/go-driver#83]
Hey guys, do you have any recommendations on how to approach this task?
I need to manage a pool of connections in a multi-tenancy environment, means I have multiple DBs to talk to. Since I cannot afford creating a new Db connection upon each request, I have to create a pool of connections.

The way how DB connection is meant to be created is to:
1. conn, err := graphHTTP.NewConnection(...)
2. c, err := graphDriver.NewClient(...) 
3. db, err := p.cl.Database(...) 

Implementation of the #3 uses a copy of the conn from #1. What it means to me is that even if I maintain my own pool of the db objects, every single one will hold a copy of the identical connections (in fact it's a connection pool). Since Database constructor is defined as private (newDatabase), even if I want to write my own implementation of #3 (with a pointer to the conn), I cannot bypass it.

Any suggestion on how to address the issue?

**Comment by ewoutp** [comment]
Hi, note that the `Connection` you pass in is an interface, not an object.
Now it is safe to use that single `Connection` many times, since internally is used a standard `http.Transport` (from the go library) that already does connection pooling for you.

Does this answer your question?

**Comment by vanobig** [comment]
I'm sorry but I still don't get it.
`Connection` is a property of the `Client`, right? And it's of `Connection` and not `*Connection`.
If I make this call 5 times
`db, err := c.Database(context.Background(), databaseName)` every instance of `db` will have its own copy of the `Connection`. Am I missing anything?

**Comment by ewoutp** [comment]
`Connection` is an interface. It is implemented by something like `*httpConnection`

**Comment by vanobig** [comment]
I guess I've learned something new about interfaces today @ewoutp.
Thank you for explaining that.
