### ISSUE TITLE
An example of a transactional request

### ISSUE THREAD

**Issue by vanobig** [arangodb/go-driver#84]
Documentation does not say anything about how a transactional request would look like.

Looked into the driver implementation and found this
`// Transaction performs a javascript transaction. The result of the transaction function is returned.
 Transaction(ctx context.Context, action string, options *TransactionOptions) (interface{}, error)`
Is it just a typo `Transaction performs a javascript transaction`? What is `action` supposed to be?

I kind of get an idea of how transactions are implemented in ArangoDB in [general](https://docs.arangodb.com/3.0/Manual/Transactions/TransactionInvocation.html) but it would be nice to see a go-driver specific example.

**Comment by StarpTech** [comment]
Look in the tests https://github.com/arangodb/go-driver/blob/master/test/database_transaction_test.go

**Comment by vanobig** [comment]
I'm a little bit confused after looking at the tests. So, yes, "action" parameter is a string, which is a JavaScript closure. 

Can anyone explain how I'm supposed to integrate this into my app? Am I supposed to construct a JavaScript code in Go now? What if I have a business logic spread across multiple services/classes (reading and writing into different collections), how do I consolidate it all in a JavaScript string?

**Comment by StarpTech** [comment]
Yep, seem so https://github.com/arangodb/go-driver/blob/master/database.go#L58 It looks like that only javascript is supported but this is documented here https://docs.arangodb.com/3.3/Manual/Transactions/TransactionInvocation.html#execute-transaction

I'm a little bit confused too. Aren't we able to write transaction with the language and tools of the client driver? Hacking this in javascript is cool but the tooling is very bad. No auto-complete, no instant feedback etc...

**Comment by ewoutp** [comment]
I'm a bit sad to say that for now the answer is yes. You have to write your transaction in JS and pass that as a Go string to the driver.
The reason for that is that the ArangoDB API (see docs link mentioned above) supports transactions in JS only. This enables the server (or cluster) to re-execute the entire transaction automatically if it needs to retry for whatever reason).
We hope to support a more traditional style of transaction in the future with an all-Go solution.

**Comment by StarpTech** [comment]
@ewoutp this is not bearable. Arangodb looked so promising and then this. Who wants to write transaction in javascript in form of a string when you are familiar with `PHP`, `Go` or even Javascript? The other downside is that you can't interact with your business logic or other services. Neo4j provides one query language to update, query nodes and edges. If you want to start a transaction you can do it via multiple cypher querys over HTTP. I really don't understand why Arangodb I took this path.

**Comment by weinberger** [comment]
Maybe there is a misunderstanding. AQL is also transactional. You need the JS transactions only for multi query transaction. Or did I get something wrong?

**Comment by vanobig** [comment]
@weinberger I think there is no misunderstanding here. It's clear that AQL is transactional. In the mean time, number of cases when multi query transaction is needed is significant large. Unfortunately, being forced to write business logic in JS while using Go is not sustainable.

**Comment by weinberger** [comment]
That’s a pity. The idea behind our current approach was that the server can better handle conflict situations be itself. But we already started internally to plan the way to a more common approach with begin and so on with AQL. Unfortunately, there isn't an ETA yet.

**Comment by vanobig** [comment]
Understood, and thank you for letting me know.
What do you suggest @weinberger? Do you want me keep the ticket open or should I close it?

**Comment by ewoutp** [comment]
@vanobig I'm closing the issue now. Feel free to re-open if needed

**Comment by snmed** [comment]
Is there any chance to get an multi query example with a transaction in the documentation? How has the javascript query look like to commit or rollback the transaction?

Cheers sandro

**Comment by TimelyToga** [comment]
@ewoutp Now that v3.5 has introduced stream transactions, will this feature be added to the go driver?

**Comment by maja42** [comment]
I can see that there are methods BeginTransaction, CommitTransaction and AbortTransaction.
But there is no documentation that I can find anywhere.

How I'm I supposed to use those functions? Am I supposed to use those functions?
