### ISSUE TITLE
collection with "Wait for sync:" setting, Create-/UpdateDocument return: ArangoError: Code 0, ErrorNum 0

### ISSUE THREAD

**Issue by andmn** [arangodb/go-driver#96]
How to reproduce:

create a collection with "Wait for sync:" enables and try to create or update a document
`meta, err = collection.CreateDocument(ctx, doc)`
`meta, err = collection.UpdateDocument(ctx, doc.Key, doc)`

err return always an error object with "ArangoError: Code 0, ErrorNum 0". When I disable "Wait for sync:" it works as expected. 

from UpdateDocument
`if err := resp.CheckStatus(cs.okStatus(201, 202)); err != nil {`
ArangoDB returns 201 but WaitForSync is not set so CheckStatus uses 202 for check and no opts are set, I use c := db.Collection(ctx, dbCollectionName)

ArangoDB Version: 3.3.3
mmfiles ENGINE

**Comment by ewoutp** [comment]
@andmn that sounds like a bug.
We'll try to reproduce and get back to you.

**Comment by andmn** [comment]
Today I had time to extract the code to reproduce the issue, see: [synctest.go.txt](https://github.com/arangodb/go-driver/files/1823263/synctest.go.txt)

**Comment by ewoutp** [comment]
@andmn PR #109 should fix this problem.
