### ISSUE TITLE
verbatim error messages

### ISSUE THREAD

**Issue by dothebart** [arangodb/go-driver#97]
Make sure all errors thrown contain human readable error messages. 
while i.e. connecting a non running server returns a good message: `panic: Get http://localhost:8529/_db/_system/_api/database/current: dial tcp [::1]:8529: getsockopt: connection refused`
failing to authentificate with the server only gives: 
`panic: ArangoError: Code 401, ErrorNum 0` 
which (if the user doesn't know that this is a HTTP-Status code) doesn't have much value.

Please check other places for good error messages too.

**Comment by nikita-vanyasin** [comment]
Hello @dothebart 

Thanks for feedback!
We are trying to improve any existing code we touch while implementing new features or during refactoring.
Checking all existing code for human-readable errors currently is not planned. 
This specific error-case (connecting to non-running serve) now has a decent error output.
Feel free to submit any PR which improves error message readability.

Best,
Nikita
